### ISSUE TITLE
install with xerces plugin

### ISSUE THREAD

**Issue by MasterToney** [ElektraInitiative/homebrew-elektra#3]
Hello, I tried to install elektra with the xerces plugin but was not successful in doing so.

The [docs](https://www.libelektra.org/plugins/xerces#dependencies) say that it requires `Xerces-C++ 3.0.0` or newer which I installed via homebrew via `brew install xerces-c`.
When preparing to build the current master from elektra with `cmake ..` it successfully includes the plugin xerces.

I performed the following commands:

1. `brew install xerces-c`
2. `brew tap elektrainitiative/elektra`
3. `brew install --verbose elektrainitiative/elektra/elektra --with-dep-plugins`

What irritates me is that it doesn't even mention the plugin in the logs when the plugins are listed to be installed.

Looking at statement from the log `==> cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/elektra/0.9.0 -DBINDINGS='cpp' -DTOOLS='kdb' -DPLUGINS='NODEP;augeas;dbus;gitresolver;tcl;yajl;yamlcpp'`it makes me wonder if it would be enough to add xerces to the list of plugin dependencies?

**Comment by markus2330** [comment]
Thank you for reporting this problem!

@sanssecours Is this homebrew specific? Why are there no logs? CMake should at least say why it excluded the xerces plugin.

**Comment by MasterToney** [comment]
Here is the full log if it is of any interest: [install_log.txt](https://github.com/ElektraInitiative/homebrew-elektra/files/3686645/install_log.txt)

My guess would be that it is excluded since it has additional dependencies, my PR #4 fixes this for xerces.

**Comment by sanssecours** [comment]
> @sanssecours Is this homebrew specific? 

Yes.

> My guess would be that it is excluded since it has additional dependencies, my PR #4 fixes this for xerces.

That is correct. The output of `brew info elektrainitiative/elektra/elektra`:

```
…
==> Dependencies
Build: cmake ✔, doxygen ✔
Optional: augeas ✘, dbus ✔, libgit2 ✘, boost ✔, yajl ✔, yaml-cpp ✔, lua ✘, qt ✔
==> Options
--with-dep-plugins
	Build with additional plugins: augeas, dbus, gitresolver, tcl, yajl, yamlcpp
--with-lua
	Build with lua support
--with-qt
	Build GUI frontend
--HEAD
	Install HEAD version
…
```

describes the current situation pretty well I think. It might make sense to add different switches for different plugins and dependencies again. Most people probably do not want to install Boost, just because they want to use the `yajl` plugin 😊.

**Comment by markus2330** [comment]
There is definitely some problem: it should be listed in the log, either as included or excluded.

> My guess would be that it is excluded since it has additional dependencies, my PR #4 fixes this for xerces.

I am not sure about homebrew but on Linux a plugin will be built as long as the dependency is installed. If the dependency is also listed in the package manager description is not relevant. But #4 is of course important in the moment when other people start installing Elektra and want to use it together with OpenHAB.

**Comment by sanssecours** [comment]
> There is definitely some problem: it should be listed in the log, either as included or excluded.

Yep, currently it does not work as intended. If you use the option `--with-dep-plugins` the formula should also install all the dependencies for the dependent plugins.

**Comment by sanssecours** [comment]
You can now install Elektra with the Xerces plugin using the following commands:

```sh
brew tap elektrainitiative/elektra
brew install elektrainitiative/elektra/elektra --with-xerces
```

. The last command above will also install `xerces-c`, if it is not installed already.

**Comment by markus2330** [comment]
@sanssecours for me it is still open why the exclusion of xerces did not show up in the build log?

**Comment by sanssecours** [comment]
> @sanssecours for me it is still open why the exclusion of xerces did not show up in the build log?

As far as I know that was the case, since the CMake variable `PLUGINS` did not include the Xerces plugin:

```sh
cmake .. \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/elektra/0.9.0 \
      -DBINDINGS='cpp' -DTOOLS='kdb' \
      -DPLUGINS='NODEP;augeas;dbus;gitresolver;tcl;yajl;yamlcpp'
```

.

**Comment by markus2330** [comment]
Ok, everything clear.
